

# lista = ["abcdef", "bababc", "abbcde",
#          "abcccd", "aabcdd", "abcdee", "ababab", ]

lista = ['wlpiogsvdfecjdqmnxakudrhbz',
         'wbpioesvyfecjuqmlxaktdrhbz',
         'blviogavyfecjuqmnxaktdrhbz',
         'wlpiogsvydecjuqmnipktdrhbz',
         'wlwiogsvyfmcjuqmoxaktdrhbz',
         'wlpiogsvphecjuqmnxaktdrzbz',
         'wlpiogsvyfecjuqmnkakhdrkbz',
         'wlpiogsvyfhcjuqmnxxktddhbz',
         'wlpiogsvyfccfuqmnxgktdrhbz',
         'wlpiogsvhmecjvqmnxaktdrhbz',
         'wlpiogsvyfecjdqqnxaktdrhyz',
         'wlpiogyvycecjaqmnxaktdrhbz',
         'wlpiogsvyfecjfqmnxaktybhbz',
         'wkpiogsvyfmcauqmnxaktdrhbz',
         'wlmiolsvyfecjuqmnxaktdrhbn',
         'wlpioksvyfecjuqmnxaktdrhgs',
         'wlpiogsvyflcjuvmnxsktdrhbz',
         'wgziogsvyfecjuqmnxaktdrhoz',
         'whpingsvyeecjuqmnxaktdrhbz',
         'wlpiogsvyfecjuqgnxaktdvhlz',
         'wlpioasvtfecjuqmnxaktdahbz',
         'wlpihgsvefeceuqmnxaktdrhbz',
         'wlpiogsvyfecyuqwnxaktdghbz',
         'wlpfsgsvyfhcjuqmnxaktdrhbz',
         'wlpiogyvyfecjuqmnxalpdrhbz',
         'wlpiogsvyfescsqmnxaktdrhbz',
         'wluiogsvyfecytqmnxaktdrhbz',
         'wltiorsvyfecjuqmoxaktdrhbz',
         'wlmiogwvyfejjuqmnxaktdrhbz',
         'wlpiogsvyfycjuumnxvktdrhbz',
         'wlkiogsqyfecjqqmnxaktdrhbz',
         'wlpiogsvyfecouqmnxaktfrubz',
         'hupiogsvlfecjuqmnxaktdrhbz',
         'wlpiogsvpxecjuqmnxaksdrhbz',
         'wlpiogsvyfkcjfqmnxxktdrhbz',
         'wlpiogsjyfecjuqnnxakthrhbz',
         'wlpiogsvyfecjuqmnxaktddhdk',
         'wlpipgsvyfecjuqmnhaktdrubz',
         'wlpiogsoyfenjpqmnxaktdrhbz',
         'wlpiogsvyfecnuqmnxaxtdrmbz',
         'wlpiggsvyfjcjuumnxaktdrhbz',
         'wlppogsvyfecjuqmnxautdhhbz',
         'wlpiovbvyfecjuqmnxaktcrhbz',
         'wlpiogsvyfecjoqmnxaktdrobu',
         'wlpiohsvyfecjugmnxakthrhbz',
         'wvpiogovyfecjuqmnxakwdrhbz',
         'wlpiogsbyfecjuqmnxdktdrtbz',
         'wlpnogsvyfecjuqmnxakykrhbz',
         'wlpiogpvyfecjuqmnxvktdrhbs',
         'wlpiogsvkvecjuqmnxadtdrhbz',
         'wlkihgsvyfecjuqmnxlktdrhbz',
         'wlpilgsvyfhcjuqmnxakudrhbz',
         'wlpioksvysgcjuqmnxaktdrhbz',
         'wlpiogsvyfecorqmoxaktdrhbz',
         'wlpiogsvyfectzlmnxaktdrhbz',
         'wlpiogsvywecjuqwnqaktdrhbz',
         'wlpiowsvyfecjuqrnxaftdrhbz',
         'wlpiogsuyfecjutmnxaktnrhbz',
         'wepiowsvyfqcjuqmnxaktdrhbz',
         'wlpirgssyfecjuqmvxaktdrhbz',
         'wlyiogstyfecjuqmnxaktdrhbw',
         'wlpiogseyfecauqmnxaktdjhbz',
         'wlpioisvyfenjuqmnxakrdrhbz',
         'wlpiogsvyfrgjfqmnxaktdrhbz',
         'wlpionsvyfecjmqmjxaktdrhbz',
         'alpiggsvyfecjuqmnxaktdrhkz',
         'wlphngsvyfecjuqmnxfktdrhbz',
         'wlpiogsvyferjuqmlxakttrhbz',
         'wlniogsvefecjuqsnxaktdrhbz',
         'wlpiogsvyfncjurmnxakudrhbz',
         'wlpiogsvyfecjuqmnxaktprlaz',
         'wlpiocsvyfecjupmkxaktdrhbz',
         'wlpihgsvyfecjeqfnxaktdrhbz',
         'wlwioasvyfjcjuqmnxaktdrhbz',
         'wlpifgsvyfecjuqsnxaktdshbz',
         'wlxiogsvyrechuqmnxaktdrhbz',
         'wlpiogovyfxcjuqmnxakkdrhbz',
         'wlpiogsvyfecjkqmdxaktmrhbz',
         'wlpiogsvyfecjwqmntaktdhhbz',
         'wlpiogsvdfecjuqmmxaktbrhbz',
         'wlpiogsvyfecauqmnxaksdrhwz',
         'wlpiogsvwfecjuqznxaktorhbz',
         'wlpiogtvyfecjuqhnxakidrhbz',
         'wlpiogsvyyecjuqmnxaktdrhwt',
         'wljiogsvyfecfuqbnxaktdrhbz',
         'wlpiogsvybecjuqmnxagtdrjbz',
         'wrpiogsvyfecjuqmnuaktdrhbd',
         'wlpiogsvyfecjurmnxnltdrhbz',
         'blpvogsvyaecjuqmnxaktdrhbz',
         'bfpiogyvyfecjuqmnxaktdrhbz',
         'wlpiogsvyfecjuqinxaknddhbz',
         'wlpizgsvvfecjuqxnxaktdrhbz',
         'glpiogsvyrecjuqmnxaktdrhbr',
         'wlpiogskhfecjutmnxaktdrhbz',
         'wlpiogsvyfecmuqmnxaktdribc',
         'wlpioesvwfecjuqmnxakkdrhbz',
         'wlpionsrafecjuqmnxaktdrhbz',
         'wlsiogsvyfecjuqmnaaktdrhvz',
         'bloiogsvyfecjuqmnxakjdrhbz',
         'wlpiogsvyfecjuqenmastdrhbz',
         'wlpiogyvyfecjuqmuxakldrhbz',
         'plpiogovyfecjuvmnxaktdrhbz',
         'wlpiogsvyfebjuqmnkakvdrhbz',
         'wlziogsvyfhcjuqmngaktdrhbz',
         'wlsiogsvyfecjuqmnxaktdrzjz',
         'plbiogsvyfecfuqmnxaktdrhbz',
         'wfpiogsvyfecjuqknxaktdrhiz',
         'wlpiogjbyfecjuqmnxaktprhbz',
         'wmpiogsvyrecjcqmnxaktdrhbz',
         'wlpiogsyyfecjuqmqxaktdrbbz',
         'wlpiogsvyfecjuqknxaetdehbz',
         'wlpiogsvyfezjuqmnxakkdhhbz',
         'wlpiogsvyfecjjqvnxaktdrhiz',
         'wkpiogsvyfucjuqmnxaktdrhbd',
         'lliiogsvyfecjuqmnxaktdrhoz',
         'wlpiogsvyfecjuqmsxdktdshbz',
         'wlprogtvyfecjuqmnxaktvrhbz',
         'wlpizgssyffcjuqmnxaktdrhbz',
         'wlpioasvyfvcjuqmnxakldrhbz',
         'wlpoogsvyyecjuqmnxastdrhbz',
         'wlpiognvyfecjuqmnsaktdrhbr',
         'wlpiogsoyfecjuqmnxaktdrhho',
         'wfpiogsvydecjuqmnxaotdrhbz',
         'wlpiogsvqhecjuqmnxaktdrhhz',
         'wkpiogsvyfeojuqmnxaktdrqbz',
         'wlpiogsvyfeveuqmnxaktdshbz',
         'wlpiogbvyfecjuqmexaktdrcbz',
         'wlpxogsvyfehjsqmnxaktdrhbz',
         'wlpcogsvyfecjuqmnjakttrhbz',
         'wlpiogsvvkecjuqmnxaftdrhbz',
         'wlpiogsvffecnuqmnxaktdnhbz',
         'wlpiogsvyfecjupjnxaktdrhbr',
         'wlpqogsvyfecjuqmnxlktdphbz',
         'wlpxogsvyfecjvqmnxaktirhbz',
         'elpiogsvyfecjuqlnxaqtdrhbz',
         'wspiogsvrfecjuqmnxakadrhbz',
         'wlpiogsmyfecbuqmnxactdrhbz',
         'wlpiogsvyfecauqmnyakzdrhbz',
         'wlsiogsvyfecjuqmnxakvdrnbz',
         'wlpiogsxyfeijuqmnxakndrhbz',
         'wlpiogsvyfecjuumnxakbyrhbz',
         'wlpiogsvyfecjuqmnxhktdyhbo',
         'wlpiogsvyfecjuqqnxnjtdrhbz',
         'wapiogsvyfecjuqmnxoktdrmbz',
         'wlpiogsvyfeejvqmnxaktdrubz',
         'wlpitgsvyeectuqmnxaktdrhbz',
         'alpiogsvyfecjulmnxaktdchbz',
         'wlpiogsvyfecjuqmuxoktdrwbz',
         'wlpiogsvyfzgjuhmnxaktdrhbz',
         'wlpnogsvyfecjuqmdxaktyrhbz',
         'wlpiogsvyfecjuqmnxakthrhra',
         'wliiogsvyfecluqmnxaktdhhbz',
         'wlpiogsvyfecjuymnxaltdrhwz',
         'wlpiogsvyfeljuqmnxaktyrhbd',
         'wlpiygsvvfecjuqmfxaktdrhbz',
         'wlpiogihsfecjuqmnxaktdrhbz',
         'wlpiogjvyfecjuqmnhuktdrhbz',
         'wldiogsvyfecjiqmwxaktdrhbz',
         'wlpiogsvjfecjuqmnxaktdrgbr',
         'wlpioisvyfecjuqwnxabtdrhbz',
         'wlviogsvyfscjuqmnxqktdrhbz',
         'wlpiogsvyfecjuqmuxakbdrubz',
         'wlpiogsvyfecjuqmnxmatdrhqz',
         'wlpiogsvyfbcjuqwmxaktdrhbz',
         'wlpiogsvyfexjuqmnxuxtdrhbz',
         'wljiogsvbfecjuqmnxartdrhbz',
         'wlpvogsvyfeujuqmnxaktdmhbz',
         'wnpiogsvyfekjuqanxaktdrhbz',
         'wlprogsvyfecjuqmzxvktdrhbz',
         'wkpiogvvyfecjuqmnxaktdrabz',
         'wlpiogsvwfecjuqmnxaktkbhbz',
         'wlpiogsvyfecjlqmnxtttdrhbz',
         'wlpioqsvyfecjuqznxaktyrhbz',
         'wlpiogsvyfecjuqmnxnethrhbz',
         'wlpiogsyyfgcjuqmnxaktdrhbm',
         'wlpiopsvbfecjuqmnxaktdlhbz',
         'wloqogsvyfucjuqmnxaktdrhbz',
         'wlpiogsvmfecjuqmnxmktdrhtz',
         'wlhiogsvyfecjuhmnxaktsrhbz',
         'wlpioggvpfecjufmnxaktdrhbz',
         'wlpiogsvyfbcjuomnxaktdrhbh',
         'wlpmogsvyfecyuqmnxoktdrhbz',
         'wlpiogslyfecjuqmnxaptyrhbz',
         'tlpiogsnyfecguqmnxaktdrhbz',
         'wlpiogsvyfecjuqmnxwktwehbz',
         'wlpiogsvgfecjuqmnxaktdrabu',
         'wbpiogsvyfecjuqmnxagtdrhoz',
         'wlwipgsvyfecjuqmnxaktdrhbu',
         'wlpwogsvykeczuqmnxaktdrhbz',
         'wlpgogsvwfecjuqmnxcktdrhbz',
         'wlpiogsqyfecjuqmrxaktdrrbz',
         'wlpiogsvyfecjuqmnxakthrafz',
         'wypicgseyfecjuqmnxaktdrhbz',
         'wlpiogcvqfecjuqmnxaktdrhzz',
         'wlriogsvyfecouqmnkaktdrhbz',
         'wlpiogsvyfemjulmnxaktdrhdz',
         'flpiogadyfecjuqmnxaktdrhbz',
         'wupiogsvyfbvjuqmnxaktdrhbz',
         'wlpiogsvyfebjummnxaktdrrbz',
         'wjpiogsvyfecjuqmnxaktprybz',
         'wlpirgsvyfecjiqmnxaatdrhbz',
         'bvpiogsvyfecjuqmnxaktdrhez',
         'wlpiogsvyfxcjuqmnxykzdrhbz',
         'wlkiwgsqyfecjqqmnxaktdrhbz',
         'wepaogsvyfecjxqmnxaktdrhbz',
         'wlpiovsvyfecjjqmnxaktdmhbz',
         'wlpioysryfecjuqmnxaktdrhiz',
         'wlpizjsvyfecjuvmnxaktdrhbz',
         'dlpiogsvyfecjucmnxakbdrhbz',
         'wlpiogsccfecjrqmnxaktdrhbz',
         'wlpioggvyfecpuqmnxagtdrhbz',
         'wlpiogsvyfvcjuumlxaktdrhbz',
         'wwpiogsryfjcjuqmnxaktdrhbz',
         'wlpiogsvyfecjuqynxaktdrogz',
         'wlpiogsvyfecjpqmnxskbdrhbz',
         'wlpiogsvyfecjuhmfxaktvrhbz',
         'wlpiogevyfecjrqmnwaktdrhbz',
         'wlpiigsvyfemjuqmnxaktdrhtz',
         'wlpcogsvyfecjuqhnxakgdrhbz',
         'wupiogsvyfxcjuqmnxaktdrhgz',
         'wlsiogsvyfecjuqenxuktdrhbz',
         'wlpioglvyfecjujmexaktdrhbz',
         'wlriogsvyfeljuqmnxattdrhbz',
         'wlpiogsvyfecfuqmhxaktkrhbz',
         'wlppogsvyfecjuqmxxabtdrhbz',
         'wlniogsvyfevjuqwnxaktdrhbz',
         'wlhiogsvyfecjuqmnxactxrhbz',
         'ilpiogivyflcjuqmnxaktdrhbz',
         'wlpmogsvyfecjuqmnxaktdrlbs',
         'wipiogsvyfeqjuqmnxaktrrhbz',
         'wvpiogsvyfecjuqknxaktdrrbz',
         'wwpioguvyfecxuqmnxaktdrhbz',
         'wlpiogsvkfdcjuqmnxaktdzhbz',
         'wlpiogfvyfecjuqmnxadtdrhbg',
         'wlpiogsvyzefjuqfnxaktdrhbz',
         'wlpiogstyfechuqmnxaktdchbz',
         'wlpiogszyfedjuqmnxsktdrhbz',
         'wzpiozsvyfncjuqmnxaktdrhbz',
         'xlpiogsvyfefjuqmnmaktdrhbz',
         'wlpiogsvyfebxummnxaktdrhbz',
         'wlpiogsgyfecfurmnxaktdrhbz',
         'wlpqogsvyfecjuomnxaktdrhbi',
         'wlpiogjvufecjuqmnxaktdrhbd',
         'wlpiolsvyfecduqmnxaktrrhbz',
         'wlpxogsvyfecjuqmnxaktgrhbk',
         'wlpiogsfyfncjuqmnxsktdrhbz',
         'wlpioggvyfecjufmnxaktdrebz',
         'wlpiogsvyfecfujmnxaktdrwbz',
         'rlpiogsvyfecjlqmnxaktdqhbz',
         'wlpfogsvyfecjuimnxaktfrhbz'
         ]

letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l',
           'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
num1 = 0
num2 = 0


def double(word):
    for i in letters:
        amount = word.count(i)
        if amount == 2:
            break
    return amount


def tripple(word):

    for i in letters:
        amount = word.count(i)
        if amount == 3:
            break
    return amount


for n in lista:
    if double(n) == 2 and tripple(n) == 3:
        num1 += 1
        num2 += 1
    elif double(n) == 2:
        num1 += 1
    elif tripple(n) == 3:
        num2 += 1
print(num1)
print(num2)
print(num1*num2)
